# Generated by Django 3.2 on 2021-05-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='libelle',
            new_name='name',
        ),
    ]
